team_42_web/team_42_web/authorization/urls.py
from django.contrib import admin
from django.urls import path, include
from authorization import views

app_name='authorization'

urlpatterns = [    
    path('index/',views.index,name='index'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    #path('teacher-registration/',views.teacherRegistartion,name='teacher_register'),
    path('teacher-form/',views.teacher_form,name='teacher-form'),
    path('student-teacher-form/',views.student_teacher_form,name='student_teacher_form'),
    path('activity-page/',views.index,name='activity'),
    path('teacher-form/',views.teacher_form,name='teacher'),
    path('class_observation/',views.index,name='class_observation'),
    path('layout-static/',views.index,name='layout-static'),
    path('layout-sidenav-light/',views.index,name='layout-sidenav-light'),
    path('activity_page/',views.index,name='activity-page'),
    path('class-room-observation/',views.class_room_observation,name='class_room_observation'),
    path('charts/',views.index,name='charts'),
    path('tables/',views.index,name='tables'),
    path('401/',views.index,name='401'),
    path('404/',views.index,name='404'),
    path('500/',views.index,name='500'),
    
]

team_42_web/team_42_web/team_42_web/urls.py
from django.contrib import admin
from django.urls import path, include
from authorization import views, urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('authorization/',include('authorization.urls',namespace='authorization')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_42_web/team_42_web/authorization/models.py
from django.db import models

# Create your models here.

team_42_web/team_42_web/authorization/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.urls import reverse, reverse_lazy

from django.urls import reverse
import os
import pyrebase

###### Firestore #######
from firebase import firebase
import firebase_admin
from firebase_admin import credentials, firestore, auth
########################
config = {
    "apiKey": "AIzaSyBPDBNI4BoXYX2l_m0Ak7s3vn4B3AbKsPo",
    "authDomain": "cfg42-fe337.firebaseapp.com",
    "databaseURL": "https://cfg42-fe337.firebaseio.com",
    "projectId": "cfg42-fe337",
    "storageBucket": "cfg42-fe337.appspot.com",
    "messagingSenderId": "500919872728",
    "appId": "1:500919872728:web:6c411b714dd01c2b187bad",
    "measurementId": "G-331ZH26DLW"
}

firebase = pyrebase.initialize_app(config)
firebase_auth = firebase.auth()
database = firebase.database()


#############FIRESTORE##############

cred = credentials.Certificate(
    os.path.join(os.path.dirname(__file__), "ServiceAccountKey.json")
    
)
default_app = firebase_admin.initialize_app(cred)
print(    os.path.join(os.path.dirname(__file__), "ServiceAccountKey.json")
)
db = firestore.client()

current_user_uid = ""

######################################

def index(request):
    print(request.session.get('uid'))
    if request.session.get('uid')==None:
        return render(request,'authorization/login.html',{})
    print(request.session['type'])
    return render(request,'frontend/dist/index.html',{})

def user_register(request):
    
    email = request.POST.get('email')
    email = str(email).rstrip(' \t\r\n\0') #new line added here --------
    password = request.POST.get('password')

    print('email',email)
    print('password',password)
    t = request.POST.get('type')
    print(t)
    try:
        user = firebase_auth.create_user_with_email_and_password(email, password)        
        #print(user)
        uid = user['localId']
        email = user['email']
        request.session['uid'] = str(uid)
        request.session['email'] = str(email)
        data = {"email":email, "password" : password}
        db.collection(u"Users").document(email).set(data)
        print(request.session.get('uid'))
        data = {"email":email, "password" : password,"type":t}
        db.collection(u"Users").document(email).set(data)
        request.session['type'] = str(t)
        user = firebase_auth.sign_in_with_email_and_password(email, password)
    except :
        message = "Invalid Login Credentials"
        return render(request,'authorization/register.html', {'message':message})
    
    return redirect('index')

def user_login(request):

    email = request.POST.get('email')
    email = str(email).rstrip(' \t\r\n\0') #new line added here --------
    password = request.POST.get('password')
    
    print('email',email)
    print('password',password)
    user=None
    if email==None or password==None:
        pass

    try:
        user = firebase_auth.sign_in_with_email_and_password(email, password)
        #print(user)
        uid = user['localId']
        email = user['email']
        request.session['uid'] = str(uid)
        request.session['email'] = str(email)
        t = db.collection("Users").document(email).get()

        request.session['type']=t.to_dict().get('type')
        print(request.session['type'])
        ###Get the type of person from database
        #data = db.collection("Users").document(email).get()
        #print(data.val())
        #request.session['type'] = str(t)
        print(request.session['type'])
        return render(request,'authorization/index.html',{'email':request.session.get('email')})
    except :
        message = "Invalid Login Credentials"
        return render(request,'authorization/login.html', {'message':message})
    #request.session['type'] = database.child("type").child("email").get()
    return render(request,'authorization/index.html',{'email':request.session.get('email')})
 

def user_logout(request):
    del request.session['uid']
    del request.session['email'] 
    del request.session['type'] 
    print(request.session.get('uid'))     
    firebase_auth.current_user = None
    print(request.session)
    return render(request, "authorization/login.html",{})

#def getClassNames(request):

# def teacherRegistartion(request):
#     data = { "fname" : request.POST.get('fname'),
#             "lname" : request.POST.get('lname'),
#             "addr" : request.POST.get('addr'),
#             "city" : request.POST.get('city'),
#             "state" : request.POST.get('state'),
#             "zip" : request.POST.get('zip'),
#             "class" : request.POST.get('title'),
#             "school" :request.POST.get('school'),
#             "phone" :request.POST.get('phone') }
#     try:
#         unid = request.session['uid']
#         database.child("unid").set(data)
    
#     except :
#         message = "Can't Update Your Details"
#         return render(request , 'authorization/teacherRegistration.html' , {'message' : message})
#     return render(request,'authorization/teacherRegistration.html',{})


def teacher_form(request):
    if request.method=='POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        field1 = request.POST.get('field1')
        field2 = request.POST.get('field2')
        field3 = request.POST.get('field3')
        school = request.POST.get("school")
        
        data = { "fname" : fname,
                "lname" : lname,
                "email" : email,
                "field1" : field1,
                "field2" : field2,
                "field3" : field3,
                "school" : school,
                }
        
        
        print(data)
        if email==None:
            return render(request,'authorization/teacher_form.html', {})
        try:
            
            db.collection(u"Admin_data").document("School1").collection("Teachers").document(fname).set(data)
            print(request.session.get('uid'))
            return render(request,'authorization/index.html', {})
        except :
            message = "Could not send data"
            print(message)
            return render(request,'authorization/teacher_form.html', {})
    return render(request,'authorization/teacher_form.html', {})
    #return redirect('index')

def student_teacher_form(request):
    if request.method=='POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        field1 = request.POST.get('field1')
        field2 = request.POST.get('field2')
        field3 = request.POST.get('field3')
        school = request.POST.get("school")
        
        data = { "fname" : fname,
                "lname" : lname,
                "email" : email,
                "field1" : field1,
                "field2" : field2,
                "field3" : field3,
                "school" : school,
                }
        
        
        print(data)
        if email==None:
            return render(request,'authorization/student_teacher_form.html', {})
        try:
            
            db.collection("Admin_data").document("School1").collection("Student_teachers").document(email).set(data)
            
            return render(request,'authorization/index.html', {})
        except :
            message = "Could not send data"
            print(message)
            return render(request,'authorization/student_teacher_form.html', {})
    return render(request,'authorization/student_teacher_form.html', {})
    #return redirect('index')

def class_room_observation(request):

    doc_ref=db.collection(u"Admin_data").document("School1").collection("Teachers").document("a")
    doc = doc_ref.get()
    
    data = doc.to_dict()
    data_arr = {"data1":data,"data2":data,"data3":data}
    print(data_arr)
    
    return render(request,'frontend/dist/classobservation.html',{"data_arr":sorted(data_arr.items())})
        


def studentRegistration(request):
    data = { "fname" : request.POST.get('fname'),
                "lname" : request.POST.get('lname'),
                "addr" : request.POST.get('addr'),
                "city" : request.POST.get('city'),
                "state" : request.POST.get('state'),
                "zip" : request.POST.get('zip'),
                "classs" : request.POST.get('class'),
                "school" :request.POST.get('school'),
                "phone" :request.POST.get('phone') }
    try:
        
        db.collection(u"Admin_data").document("School1").collection("Student").document(fname).set(data)
        print(request.session.get('uid'))
    except :
         message = "Could not send data"
         print(message)
         return render(request,'authorization/studentRegForm.html', {})
    return redirect('index')
    

team_42_web/team_42_web/templates/authorization/charts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Charts - SB Admin</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'authorization:index' %}">Start Bootstrap</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        {% if request.session.uid %}
                        <a class="dropdown-item" href="{% url 'authorization:logout' %}">Logout</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'authorization:login' %}">Login</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'authorization:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Layouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'authorization:layout-static' %}">Static Navigation</a>
                                    <a class="nav-link" href="{% url 'authorization:layout-sidenav-light' %}">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            {% if request.session.uid %}
                                            <a class="nav-link" href="{% url 'authorization:logout' %}">Logout</a>
                                            {% else %}
                                            <a class="nav-link" href="{% url 'authorization:login' %}">Login</a>
                                            <a class="nav-link" href="{% url 'authorization:register' %}">Register</a>
                                            {% endif %}
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <!-- <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div> -->
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="{% url 'authorization:charts' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="{% url 'authorization:tables' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Charts</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="{% url 'authorization:index' %}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Charts</li>
                        </ol>
                        <div class="card mb-4">
                            <div class="card-body">
                                Chart.js is a third party plugin that is used to generate the charts in this template. The charts below have been customized - for further customization options, please visit the official
                                <a target="_blank" href="https://www.chartjs.org/docs/latest/">Chart.js documentation</a>
                                .
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-chart-area mr-1"></i>
                                Area Chart Example
                            </div>
                            <div class="card-body"><canvas id="myAreaChart" width="100%" height="30"></canvas></div>
                            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar mr-1"></i>
                                        Bar Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myBarChart" width="100%" height="50"></canvas></div>
                                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-pie mr-1"></i>
                                        Pie Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myPieChart" width="100%" height="50"></canvas></div>
                                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-pie-demo.js' %}"></script>
    </body>
</html>

team_42_web/team_42_web/templates/authorization/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Register</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Pheonix42</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authorization:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authorization:login' %}">Login</a>                  
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authorization:register' %}">Register</a>
                </li>
                
              </ul>
            </div>
          </nav>

        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-7">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Account</h3></div>
                                    <div class="card-body">
                                        <form method="POST" action="{% url 'authorization:register' %}">
                                            {% csrf_token %}
                                            <div class="form-row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputFirstName">First Name</label>
                                                        <input class="form-control py-4" id="inputFirstName" type="text" placeholder="Enter first name" name="first-name" />
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputLastName">Last Name</label>
                                                        <input class="form-control py-4" id="inputLastName" type="text" placeholder="Enter last name" name="last-name" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                <input class="form-control py-4" id="inputEmailAddress" type="email" aria-describedby="emailHelp" placeholder="Enter email address" name="email"/>
                                            </div>
                                            <div class="form-row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputPassword">Password</label>
                                                        <input class="form-control py-4" id="inputPassword" type="password" placeholder="Enter password" name="password"/>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form group">
                                                        <label for="cars">Choose your Post:</label>

                                                        <select name="type" id="position" >
                                                        <option value="Student Mentor">Student Mentor</option>
                                                        <option value="Admin">Admin</option>
                                                        <option value="Teacher">Teacher</option>
                                                        
                                                        </select>
                                                      </div>
                                                </div>
                                            </div>
                                            <div class="form-group mt-4 mb-0">
                                                <input type="submit" class="btn btn-primary btn-block" href="{% url 'authorization:register' %}" value="Create Account">
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'authorization:login' %}">Have an account? Go to login</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>